name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/font/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/font/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/font/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/font/LexendDeca-Bold.ttf
          weight: 700
